version: '3'

services:
  mongo:
    container_name: confac-${ENVIRONMENT}-mongo
    build:
      context: ./mongo-seed
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "${MONGO_DATA_VOLUME}:/data/db"
    ports:
      - "${MONGO_PORT}:27017"
    expose:
      - ${MONGO_PORT}
    networks:
      - confacnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_POWERBI_USER: ${MONGO_POWERBI_USER}
      MONGO_POWERBI_PWD: ${MONGO_POWERBI_PWD}


  app:
    container_name: "confac-${ENVIRONMENT}-app"
    build: .
    image: confac-app:${TAG}
    restart: always
    volumes:
      - "${TEMPLATE_PATH}:/templates"
      - "${FONT_PATH}:/usr/share/fonts"
    ports:
      - "${APP_PORT}:7000"
    networks:
      - confacnet
    environment:
      ENABLE_ROOT_TEMPLATES: 1
      SERVER_HOST: localhost
      SERVER_BASEPATH: ""
      PORT: 7000
      MONGO_HOST: mongo
      MONGO_DB: ${MONGO_DB}
      MONGO_PORT: 27017
      MONGO_USERNAME: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PWD}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GOOGLE_DOMAIN: ${GOOGLE_DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES: ${JWT_EXPIRES}
      SUPERUSER: ${SUPERUSER}
      DEFAULT_ROLE: ${DEFAULT_ROLE}
      ENVIRONMENT: ${ENVIRONMENT}
      BUILD_VERSION: ${TAG}
      LOGGING_FILE: ${LOGGING_FILE}
      LOGGING_LOKI: ${LOGGING_LOKI}
    depends_on:
      - mongo

networks:
  confacnet:
    driver: bridge
